Repository wecode-bootcamp-korea/11-weline-frontend, pull requests merged in 2020-08, with the labels that each got.

#4 Add: PaymentEmail 기본 레이아웃 구성 완료
  package-lock.json
  package.json
  public/Data/mockData/Goods.json
  public/Images/JACKET.jpg
  public/Images/necktie.jpg
  public/Images/phone.png
  public/Images/unnamed.png
  src/Components/EmailGoods.js
  src/Components/EmailGoods.scss
  src/Components/EmailGoodsList.js
  src/Pages/WishList/PaymentEmail.js
  src/Pages/WishList/PaymentEmail.scss
  src/index.js
Labels: Status: Accepted

#7 Modify: 세로 스크롤 기능 추가
  public/Data/MockData/Goods.json
  src/Components/Goods.js
  src/Components/GoodsList.js
  src/Pages/Shop/ShopListCol.js
Labels: Status: Accepted

#10 [한태규]Modify: mockdata 중첩오류 수정을 위한 파일 삭제
  public/Data/mockData/Goods.json
  public/Data/none.json
Labels: Status: Accepted

#2 [이영섭] Refactor:리뷰 반영 (feature/ShopDetails)
  src/Pages/Nav/Menu2.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Pages/Shop/Option.js
  src/Pages/Shop/Option.scss
  src/Pages/Shop/ShopDetails.js
  src/Pages/Shop/ShopDetails.scss
  src/Pages/Shop/ShopDetailsData.js
  src/Pages/Shop/TempText.js
  src/Styles/common.scss
  src/config.js
Labels: Status: Accepted

#8 [이영섭] Refactor: 리뷰 반영 (feature/Nav)
  public/Data/MockData/SearchData.json
  src/Pages/Main/Main.js
  src/Pages/Nav/FirstSubMenu.js
  src/Pages/Nav/Menu2.js
  src/Pages/Nav/MenuData.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Pages/Nav/SearchResultItem.js
  src/Pages/Nav/SearchResultItem.scss
  src/Pages/Nav/SecondSubMenu.js
  src/Pages/Women/Boots.js
  src/Pages/Women/Shoes.js
  src/Pages/Women/Shoes.scss
  src/Pages/Women/Women.js
  src/Pages/Women/Women.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#14 [한태규]Modify: 결제 페이지 기본 구현사항
  public/Data/mockData/SearchData.json
  public/Data/mockData/accordian.json
  src/Pages/WishList/CheckOut.js
  src/Pages/WishList/CheckOut.scss
  src/Pages/WishList/Payment.js
  src/Pages/WishList/Payment.scss
  src/Pages/WishList/ShoppingMethod.js
  src/Pages/WishList/ShoppingMethod.scss
Labels: Status: 리뷰 요청

#9 [박진아] Add: login page 레이아웃
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/components/ForgotPw.js
  src/Pages/Login/components/LoginTab.js
  src/Pages/Login/components/LoginTab.scss
  src/Pages/Login/components/SignUpTab.js
  src/Pages/Login/components/SignUpTab.scss
  src/Pages/Login/components/loginTab copy.scss
  src/Routes.js
Labels: Status: 수정 요청

#13 [박진아] Add: runways 레이아웃 추가
  pull_request_template.md
  src/Pages/Runways/Runways.js
  src/Pages/Runways/Runways.scss
  src/Pages/Runways/components/Card.js
  src/Pages/Runways/components/Card.scss
  src/Routes.js
Labels: Status: 수정 요청

#17 [박진아] Add: runways에 nav 추가
  src/Pages/Nav/FirstSubMenu.js
  src/Pages/Runways/Runways.js
  src/Pages/Runways/Runways.scss
  src/Pages/Runways/components/Card.js
  src/Pages/Runways/components/Card.scss
Labels: Status: 리뷰 요청

#16 Add: 동적 라우팅 적용
  src/Pages/Nav/FirstSubMenu.js
  src/Pages/Nav/MenuData.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/SecondSubMenu.js
  src/Pages/Shop/ShopDetails.js
  src/Pages/Shop/ShopDetailsData.js
  src/Pages/Title/Category.js
  src/Pages/Title/MainCategory.js
  src/Pages/Title/MainCategory.scss
  src/Pages/Title/Title.js
  src/Pages/Title/Title.scss
  src/Pages/Women/Shoes.js
  src/Pages/Women/Women.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#3 [Weline 이도윤] Add: ShopList (가로스크롤) 페이지 구현
  public/Font/NeueHaasGroteskText-Bold.otf
  public/Font/NeueHaasGroteskText-Medium.otf
  public/Font/NeueHaasGroteskText-Regular.otf
  public/Images/ShopListRow/1.webp
  public/Images/ShopListRow/10.webp
  public/Images/ShopListRow/11.webp
  public/Images/ShopListRow/12.webp
  public/Images/ShopListRow/2.webp
  public/Images/ShopListRow/3.webp
  public/Images/ShopListRow/4.webp
  public/Images/ShopListRow/5.webp
  public/Images/ShopListRow/6.webp
  public/Images/ShopListRow/7.webp
  public/Images/ShopListRow/8.webp
  public/Images/ShopListRow/9.webp
  public/Images/WishList/blouse1.webp
  public/Images/WishList/blouse2.webp
  public/Images/WishList/blouse3.webp
  public/Images/WishList/boots1.webp
  public/Images/WishList/boots2.webp
  public/Images/WishList/boots3.webp
  public/Images/WishList/boots4.webp
  public/Images/WishList/jewerly1.webp
  public/Images/WishList/jewerly2.webp
  public/Images/WishList/jewerly3.webp
  public/Images/WishList/leather1.webp
  public/Images/WishList/leather2.webp
  public/Images/WishList/leather3.webp
  public/Images/WishList/leather4.webp
  public/Images/WishList/noitem.jpg
  public/Images/WishList/perfume1.webp
  public/Images/WishList/perfume2.webp
  public/Images/WishList/perfume3.webp
  public/Images/WishList/perfume4.webp
  public/Images/WishList/vest1.webp
  public/Images/WishList/vest2.webp
  public/Images/WishList/vest3.webp
  public/shoplistrow.json
  public/wishlist.json
  src/Pages/Shop/ShopListRow.js
  src/Pages/Shop/ShopListRow.scss
  src/Pages/Shop/ShopListRowItem.js
  src/Pages/Shop/ShopListRowItems.js
  src/Pages/Shop/ShopListRowItems.scss
  src/Pages/WishList/WishItem.js
  src/Pages/WishList/WishList.js
  src/Pages/WishList/WishList.scss
  src/Pages/WishList/child.js
  src/Pages/WishList/parent.js
Labels: Status: 리뷰 요청

#18 [이영섭] Modify: css 수정 및 버튼 경로 변경
  src/Components/Video/Video.scss
  src/Pages/Login/Login.js
  src/Pages/Main/MainData.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Pages/Shop/ProductDetails.js
  src/Pages/Shop/ProductDetails.scss
  src/Pages/Shop/ShopDetails.js
  src/Pages/Shop/ShopDetails.scss
Labels: Status: 리뷰 요청

#19 [한태규]Modify: 동적라우팅 주소변경시 내용변경을 위한 컴디업 추가
  public/Data/mockData/accordian.json
  src/Components/Goods.js
  src/Components/GoodsList.js
  src/Components/ShopTab.js
  src/Pages/Nav/FirstSubMenu.js
  src/Pages/Nav/MenuData.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Pages/Shop/Shop.js
  src/Pages/Shop/Shop.scss
  src/Pages/Shop/ShopDetails.js
  src/Pages/Shop/ShopListCol.js
  src/Pages/Title/Category.js
  src/Pages/Title/MainCategory.js
  src/Pages/Title/MainCategory.scss
  src/Pages/Title/Title.js
  src/Pages/WishList/CheckOut.js
  src/Pages/WishList/CheckOut.scss
  src/Pages/WishList/Payment.js
  src/Pages/WishList/Payment.scss
  src/Pages/WishList/ShoppingMethod.js
  src/Pages/WishList/WishList.js
  src/Pages/WishList/WishList.scss
  src/Pages/WishList/child.js
  src/Pages/WishList/parent.js
Labels: Status: 리뷰 요청
